#!/bin/bash

convert -background white -fill black -pointsize 16 label:"alexandre.levada@ufscar.br" alexandre.levada.png
convert -background white -fill black -pointsize 16 label:"aroca@ufscar.br" aroca.png
convert -background white -fill black -pointsize 16 label:"auri@ufscar.br" auri.png
convert -background white -fill black -pointsize 16 label:"cerri@ufscar.br" cerri.png
convert -background white -fill black -pointsize 16 label:"comin@ufscar.br" comin.png
convert -background white -fill black -pointsize 16 label:"daniel.lucredio@ufscar.br" daniel.lucredio.png
convert -background white -fill black -pointsize 16 label:"darli@dc.ufscar.br" darli.png
convert -background white -fill black -pointsize 16 label:"delano@dc.ufscar.br" delano.png
convert -background white -fill black -pointsize 16 label:"desouza@ufscar.br" desouza.png
convert -background white -fill black -pointsize 16 label:"diegofs@ufscar.br" diegofs.png
convert -background white -fill black -pointsize 16 label:"ednaldo@dc.ufscar.br" ednaldo.png
convert -background white -fill black -pointsize 16 label:"emerson@dc.ufscar.br" emerson.png
convert -background white -fill black -pointsize 16 label:"fcferrari@ufscar.br" fcferrari.png
convert -background white -fill black -pointsize 16 label:"felice@ufscar.br" felice.png
convert -background white -fill black -pointsize 16 label:"ferrari@ufscar.br" ferrari.png
convert -background white -fill black -pointsize 16 label:"fredy@ufscar.br" fredy.png
convert -background white -fill black -pointsize 16 label:"helenacaseli@ufscar.br" helenacaseli.png
convert -background white -fill black -pointsize 16 label:"helio@dc.ufscar.br" helio.png
convert -background white -fill black -pointsize 16 label:"heloisa@dc.ufscar.br" heloisa.png
convert -background white -fill black -pointsize 16 label:"hendrik.soares@gmail.com" hendrik.soares.png
convert -background white -fill black -pointsize 16 label:"hermes@ufscar.br" hermes.png
convert -background white -fill black -pointsize 16 label:"jander@ufscar.br" jander.png
convert -background white -fill black -pointsize 16 label:"joice@dc.ufscar.br" joice.png
convert -background white -fill black -pointsize 16 label:"kato@ufscar.br" kato.png
convert -background white -fill black -pointsize 16 label:"luciano@dc.ufscar.br" luciano.png
convert -background white -fill black -pointsize 16 label:"macccdias@gmail.com" macccdias.png
convert -background white -fill black -pointsize 16 label:"marcela@dc.ufscar.br" marcela.png
convert -background white -fill black -pointsize 16 label:"marcella@ufscar.br" marcella.png
convert -background white -fill black -pointsize 16 label:"marcio@dc.ufscar.br" marcio.png
convert -background white -fill black -pointsize 16 label:"mariana@dc.ufscar.br" mariana.png
convert -background white -fill black -pointsize 16 label:"marilds.santos@ufscar.br" marilde.santos.png
convert -background white -fill black -pointsize 16 label:"matias@ufscar.br" matias.png
convert -background white -fill black -pointsize 16 label:"mauricio@ufscar.br" mauricio.png
convert -background white -fill black -pointsize 16 label:"menotti@ufscar.br" menotti.png
convert -background white -fill black -pointsize 16 label:"murillo@ufscar.br" murillo.png
convert -background white -fill black -pointsize 16 label:"naldi@ufscar.br" naldi.png
convert -background white -fill black -pointsize 16 label:"secretaria.graduacao.dc@ufscar.br" nicanor.png
convert -background white -fill black -pointsize 16 label:"orides@ufscar.br" orides.png
convert -background white -fill black -pointsize 16 label:"pcdparis@ufscar.br" pcdparis.png
convert -background white -fill black -pointsize 16 label:"politano@ufscar.br" politano.png
convert -background white -fill black -pointsize 16 label:"renato@ufscar.br" renato.png
convert -background white -fill black -pointsize 16 label:"rferrari@ufscar.br" rferrari.png
convert -background white -fill black -pointsize 16 label:"rrc@ufscar.br" rrc.png
convert -background white -fill black -pointsize 16 label:"rsinoue@ufscar.br" rsinoue.png
convert -background white -fill black -pointsize 16 label:"sandra@ufscar.br" sabib.png
convert -background white -fill black -pointsize 16 label:"secretaria.graduacao.dc@ufscar.br" secretaria.graduacao.dc.png
convert -background white -fill black -pointsize 16 label:"ppgcc@ufscar.br" secretaria.ppgcc.png
convert -background white -fill black -pointsize 16 label:"valtervcamargo@ufscar.br" valtervcamargo.png
convert -background white -fill black -pointsize 16 label:"vania@dc.ufscar.br" vania.png
convert -background white -fill black -pointsize 16 label:"vera@dc.ufscar.br" vera.png
convert -background white -fill black -pointsize 16 label:"vivaldini@dc.ufscar.br" vivaldini.png
convert -background white -fill black -pointsize 16 label:"willian@ufscar.br" willian.png
convert -background white -fill black -pointsize 16 label:"zorzo@ufscar.br" zorzo.png